
CREATE TABLE STUDENT_TBL(
    STUDENT_ID VARCHAR2(15),
    STUDENT_PWD VARCHAR2(15),
    STUDENT_NAME VARCHAR2(20),
    GENDER CHAR(1),
    AGE NUMBER,
    EMAIL VARCHAR2(30),
    PHONE CHAR(11),
    ADDRESS VARCHAR2(500),
    HOBBY VARCHAR2(50),
    ENROLL_DATE DATE
);

ALTER TABLE STUDENT_TBL
ADD CONSTRAINT STUDENT_PK PRIMARY KEY(STUDENT_ID);

ALTER TABLE STUDENT_TBL
ADD CHECK(GENDER IN('M', 'F'));

ALTER TABLE STUDENT_TBL
MODIFY AGE NOT NULL;

ALTER TABLE STUDENT_TBL
MODIFY STUDENT_NAME NOT NULL;

ALTER TABLE STUDENT_TBL
MODIFY STUDENT_PWD NOT NULL;

INSERT INTO STUDENT_TBL
VALUES ('admin', 'admin', '관리자', 'M', 30, 'admin@iei.or.kr', '01094111994', '서울시 중구 남대문로', '코딩,독서,운동', SYSDATE);

COMMIT;

INSERT INTO STUDENT_TBL
VALUES('khuser01', 'pass01', '일용자', 'M', 21,
'khuser01@kh.com','01092920303', '서울시 종로구', '수영,걷기', SYSDATE);
UPDATE STUDENT_TBL SET STUDENT_ID = '1' WHERE STUDENT_ID = '2';
SELECT * FROM STUDENT_TBL;
COMMIT;


CREATE TABLE MEMBER_TBL(
    MEMBER_ID VARCHAR2(20),
    MEMBER_PWD VARCHAR2(30),
    MEMBER_NAME VARCHAR2(20),
    MEMBER_GENDER VARCHAR2(3),
    MEMBER_AGE NUMBER,
    MEMBER_EMAIL VARCHAR2(30),
    MEMBER_PHONE VARCHAR2(11),
    MEMBER_ADDRESS VARCHAR2(100),
    MEMBER_HOBBY VARCHAR2(50),
    MEMBER_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
    -- SYSTIMESTAMP 시분초 함께 저장되는 날짜 데이터형 
);

DROP TABLE MEMBER_TBL;

-- MEMBER_ID에 PRIMARY KEY 제약조건 추가
ALTER TABLE MEMBER_TBL
ADD CONSTRAINT PK_MEMBERID2 PRIMARY KEY(MEMBER_ID);

-- MEMBER_PWD에 NOT NULL 제약조건 추가 (NOT NULL은 MODIFY를 사용한다)
ALTER TABLE MEMBER_TBL
MODIFY MEMBER_PWD NOT NULL;

-- MEMBER_NAME에 NOT NULL 제약조건 추가 (NOT NULL은 MODIFY를 사용한다) 
ALTER TABLE MEMBER_TBL
MODIFY MEMBER_NAME NOT NULL;

-- MEMBER_GENDER에 CHECK('남','여') 제약조건 추가
ALTER TABLE MEMBER_TBL
ADD CHECK(MEMBER_GENDER IN ('남','여'));

SELECT * FROM USER_CONSTRAINTS;

INSERT INTO MEMBER_TBL VALUES ('ADMIN' , 'ADMIN' , '관리자', '남', 33, 'ADMIN@NAVER.COM', '01012345678', '서울시 종로구', '독서', DEFAULT); 
DESC MEMBER_TBL;
SELECT * FROM MEMBER_TBL;
COMMIT;

SELECT * FROM MEMBER_TBL;

